INSERT INTO stations (name, url, favorite)
VALUES
  ('105', 'https://icecast.unitedradio.it/Radio105.mp3', 1),
  ('Rtl-102.5', 'https://streamingv2.shoutcast.com/rtl-1025', 0),
  ('Virgin', 'https://icecast.unitedradio.it/Virgin.mp3', 0),
  ('Subasio', 'https://icy.unitedradio.it/Subasio.mp3', 0),
  ('Montecarlo 2', 'https://edge.singsingmusic.net/MC2.mp3', 0),
  ('Rai 1', 'https://icestreaming.rai.it/1.mp3', 0),
  ('Rai 2', 'https://icestreaming.rai.it/2.mp3', 0),
  ('Rai 3', 'https://icestreaming.rai.it/3.mp3', 0),
  ('kiss', 'https://kisskiss.fluidstream.eu/KKItalia.aac?FLID=8', 0),
  ('Sport', 'https://mediahit.inmystream.it:9000/stream', 0),
  ('Latte e Miele', 'https://ice02.fluidstream.net/fluid016.aac?FLID=', 0),
  ('Arancia Network', 'https://stream3.xdevel.com/audio0s975447-156/stream/icecast.audio', 0),
  ('Rai Tutta Italiana','http://icestreaming.rai.it/4.mp3', 0),
  ('R101 Diretta','http://icecast.unitedradio.it/r101', 0),
  ('RTL','http://shoutcast.rtl.it:3010/', 0),
  ('RTL Best','http://shoutcast.rtl.it:3020/', 0),
  ('RTL ItalianStyle','http://shoutcast.rtl.it:3030/', 0),
  ('RTL Groove','http://shoutcast.rtl.it:3040/', 0),
  ('RTL Lounge','http://shoutcast.rtl.it:3070/', 0),
  ('RTL Radiofreccia','http://shoutcast.rtl.it:3060/', 0),
  ('Zeta L’Italiana','http://shoutcast.rtl.it:3030/stream/1/', 0),
  ('Kiss Kiss','http://wma08.fluidstream.net:4610/http://ice07.fluidstream.net:8080/KissKiss.mp3', 0),
  ('Kiss Kiss Italia','http://wma07.fluidstream.net:3616/;stream.nsv', 0),
  ('Radio Marte','http://onair18.xdevel.com:8212/', 0),
  ('Giornaleradio','https://gr.fluidstream.eu/gr1.mp3', 0);